### ISSUE TITLE
Update the UI/UX + Forms

### ISSUE THREAD

**Issue by usman-tahir** [keithb418/scrum-team-app#7]
- [x] Update UX mockup for dashboard
- [x] Create UX mockup for add Team form
- [x] Update UX mockup for add a new team member form
  - [x] Add email field to new team member form 
- [x] Create UX mockup for individual team member view
- [x] Create UX mockup for edit update individual team member form
  - [x] Add email field to new team member form
- [x] Update UX mockup for team member search
  - [x] Add search by email

**Comment by asc2683** [comment]
Updated mockup here: https://scrum-team-app.mybalsamiq.com/projects
