### ISSUE TITLE
Back End CRUD Operations

### ISSUE THREAD

**Issue by usman-tahir** [keithb418/scrum-team-app#9]

**Comment by keithb418** [comment]
- [ ] Create Mongo Operations Object
- [ ] Create basic CRUD optations for Team Object

**Comment by asc2683** [comment]
I think we can pull out object validation to the base CRUD resource. This can be an independent task/issue.

**Comment by keithb418** [comment]
We don't have object validation yet, but that can be added later as part of a separate task.
