### ISSUE TITLE
Unit tests for GET requests

### ISSUE THREAD

**Issue by asc2683** [keithb418/scrum-team-app#93]
- [ ] Add unit tests for **GET** requests
  - [ ] GET teams /api/teams
  - [ ] GET teamMembers /api/teamMembers
  - [ ] GET specific team /api/team/:id
  - [ ] GET specific team /api/teamMember/:id

Resource: https://facebook.github.io/jest/docs/en/tutorial-async.html

**Comment by Crunchwrap78** [comment]
In general there needs to be better coverage on the unit tests.
